In [1]:
import pandas as pd
import numpy as np

In [4]:
import pandas as pd
df = pd.read_csv(r"E:\Nimish PG\movies.csv")
df.head()

,movie_id,title,content_type,genre_primary,genre_secondary,release_year,duration_minutes,rating,language,country_of_origin,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,NaN,NaN,NaN,NaN,NaN,False,2023-08-07,False
1,movie_0002,Storm Warrior,Stand-up Comedy,Sci-Fi,NaN,2017,37.0,PG,Japanese,USA,3.3,NaN,NaN,NaN,NaN,False,2022-01-28,True
2,movie_0003,Fire Family,Movie,Drama,NaN,2003,142.0,TV-MA,English,USA,8.5,2114120.0,NaN,NaN,NaN,False,2021-05-04,True
3,movie_0004,Our Princess,Documentary,Sci-Fi,NaN,2011,131.0,NC-17,Japanese,USA,5.3,NaN,NaN,NaN,NaN,False,2022-11-26,False
4,movie_0005,Warrior Mission,Documentary,Sport,Mystery,2015,91.0,TV-G,English,USA,3.1,NaN,NaN,NaN,NaN,False,2023-06-15,False

In [6]:
df.columns

Index(['movie_id', 'title', 'content_type', 'genre_primary', 'genre_secondary',
       'release_year', 'duration_minutes', 'rating', 'language',
       'country_of_origin', 'imdb_rating', 'production_budget',
       'box_office_revenue', 'number_of_seasons', 'number_of_episodes',
       'is_netflix_original', 'added_to_platform', 'content_warning'],
      dtype='object')

In [7]:
df.isna().sum()
#Used to check for missing (null/NaN) values in each column of a DataFrame.

movie_id                 0
title                    0
content_type             0
genre_primary            0
genre_secondary        667
release_year             0
duration_minutes         0
rating                   0
language                 0
country_of_origin        0
imdb_rating            150
production_budget      675
box_office_revenue     709
number_of_seasons      751
number_of_episodes     719
is_netflix_original      0
added_to_platform        0
content_warning          0
dtype: int64

In [9]:
df.describe(include=[float, int])

,release_year,duration_minutes,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes
count,1040.000000,1040.000000,890.000000,3.650000e+02,3.310000e+02,289.000000,321.000000
mean,2006.416346,89.112500,6.268539,1.111541e+07,6.461093e+07,7.339100,101.052960
std,11.414524,69.298936,1.809088,2.395707e+07,1.723719e+08,4.075148,56.433149
min,1953.000000,0.000000,0.500000,6.837300e+04,2.863700e+04,1.000000,6.000000
25%,1998.000000,51.000000,5.300000,1.445488e+06,3.261451e+06,3.000000,54.000000
50%,2006.000000,81.000000,6.400000,3.778470e+06,1.131604e+07,7.000000,97.000000
75%,2016.000000,109.000000,7.400000,9.373108e+06,4.556450e+07,11.000000,152.000000
max,2024.000000,586.000000,10.000000,1.973266e+08,2.032056e+09,14.000000,199.000000

In [10]:
print(df[['content_type', 'language', 'country_of_origin']].value_counts())

content_type     language  country_of_origin
Movie            English   USA                  144
TV Series        English   USA                   80
Stand-up Comedy  English   USA                   41
Documentary      English   USA                   38
Movie            English   South Korea           30
                                               ...
Stand-up Comedy  Italian   Germany                1
                           France                 1
Movie            Hindi     South Korea            1
Documentary      Italian   UK                     1
                 Hindi     South Korea            1
Name: count, Length: 187, dtype: int64

In [18]:
print(df['content_type'].value_counts())

content_type
Movie              458
TV Series          267
Documentary        142
Stand-up Comedy    119
Limited Series      54
Name: count, dtype: int64

In [19]:
print(df.sample(5))

        movie_id         title content_type genre_primary genre_secondary  \
48    movie_0049   Kingdom Day        Movie      Thriller             NaN
45    movie_0046    The Dragon    TV Series        Family             NaN
378   movie_0379    Our Battle    TV Series        Horror             NaN
1018  movie_0468  King Phoenix    TV Series        Action         Western
980   movie_0981  First Dragon        Movie     Biography             NaN

      release_year  duration_minutes rating  language country_of_origin  \
48            2023             111.0  NC-17   English           Germany
45            2002              43.0  PG-13   English               USA
378           2007              41.0   TV-G  Japanese       South Korea
1018          1992              27.0  TV-Y7   Spanish               USA
980           2008              90.0  TV-14   English             India

      imdb_rating  production_budget  box_office_revenue  number_of_seasons  \
48            4.6           629194.0           2736647.0                NaN
45            6.7                NaN                 NaN                8.0
378           NaN                NaN                 NaN               13.0
1018          7.0                NaN                 NaN                NaN
980           5.4                NaN         144443940.0                NaN

      number_of_episodes  is_netflix_original added_to_platform  \
48                   NaN                False        2024-03-03
45                 113.0                False        2023-08-15
378                164.0                False        2021-03-23
1018               117.0                False        2023-06-17
980                  NaN                 True        2025-02-07

      content_warning
48              False
45              False
378             False
1018            False
980             False